const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const pct=v=>`${((Number(v)||0)*100).toFixed(1)}%`, num=v=>Number(v)||0;
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
const today=()=>new Date().toISOString().slice(0,10), monthKey=()=>new Date().toISOString().slice(0,7)+'-01';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

const TAX_TABLES={III:[[180000,.06,0],[360000,.112,9360],[720000,.135,17640],[1800000,.16,35640],[3600000,.21,125640],[4800000,.33,648000]],V:[[180000,.155,0],[360000,.18,4500],[720000,.195,9900],[1800000,.205,17100],[3600000,.23,62100],[4800000,.305,540000]]};
const baseProducts=[['Google Perfil da Empresa','Implantação'],['Gestão Google','Mensal'],['Site Institucional','Projeto'],['Landing Page','Projeto'],['IA Atendimento','Mensal'],['IA Comercial','Mensal'],['CRM Zahav','Mensal'],['Automação Comercial','Mensal'],['Gestão Meta Ads','Mensal'],['Google Ads','Mensal'],['Panfletagem Digital','Campanha'],['Reativação de Clientes','Campanha / Mensal']];
const baseCosts=[['Administrativo','Contabilidade','Fixo','Mensal'],['Tecnologia','Hostinger / hospedagem','Fixo','Mensal'],['Tecnologia','Lovable / desenvolvimento','Fixo','Mensal'],['Tecnologia','ChatGPT / OpenAI','Fixo','Mensal'],['Tecnologia','WhatsApp / API','Fixo','Mensal'],['Tecnologia','Supabase / servidor / automação','Fixo','Mensal'],['Tecnologia','Domínios','Fixo','Anual'],['Operação','Internet / telefone','Fixo','Mensal'],['Comercial','Deslocamento / combustível','Variável','Mensal'],['Comercial','Marketing da Zahav','Variável','Mensal'],['Financeiro','Taxas bancárias / cobrança','Variável','Mensal'],['Sócios','Pró-labore / INSS','Fixo','Mensal'],['Operação','Ferramentas diversas','Fixo','Mensal'],['Outros','Outros custos','Variável','Mensal']];

const fresh=()=>({
 version:3,settings:{company:'Zahav Digital',size:'ME',taxRegime:'Simples Nacional',taxMode:'V',rbt12:0,revenueCurrent:0,revenueProjected:0,clientsPlanned:10,hourValue:50,targetMargin:.10,payroll12:0,manualTax:.10,costAlert:.50,concentrationAlert:.35,cashOpening:0},
 costs:baseCosts.map(x=>({id:uid(),category:x[0],name:x[1],type:x[2],period:x[3],value:0,qty:1,supplier:'',center:'',notes:'',active:true})),
 products:baseProducts.map(x=>({id:uid(),name:x[0],model:x[1],price:0,hours:0,tech:0,variable:0,taxMode:'Padrão',notes:'',active:true})),
 clients:[],plans:[],scenarios:[],cashflow:[],closings:[],goals:[],audit:[],aiHistory:[]
});
function migrate(x){const d=fresh();if(!x||!x.settings)return d;return {...d,...x,version:3,settings:{...d.settings,...x.settings},costs:(x.costs||d.costs).map(c=>({...{supplier:'',center:'',notes:'',active:true},...c})),products:(x.products||d.products).map(p=>({...{active:true},...p})),clients:x.clients||[],plans:x.plans||[],scenarios:x.scenarios||[],cashflow:x.cashflow||[],closings:x.closings||[],goals:x.goals||[],audit:x.audit||[],aiHistory:x.aiHistory||[]};}
function load(){try{return migrate(JSON.parse(localStorage.getItem('zahavFinanceOS')))}catch{return fresh()}}
let state=load(),page='dashboard';
function persist(){localStorage.setItem('zahavFinanceOS',JSON.stringify(state))}
function audit(action,entity,before=null,after=null){state.audit.unshift({id:uid(),at:new Date().toISOString(),action,entity,before,after});state.audit=state.audit.slice(0,500);persist()}

function effectiveTax(rbt12,annex){rbt12=num(rbt12);if(rbt12<=0)return annex==='III'?.06:.155;const row=TAX_TABLES[annex].find(r=>rbt12<=r[0])||TAX_TABLES[annex].at(-1);return Math.max(0,(rbt12*row[1]-row[2])/rbt12)}
function taxRate(mode='Padrão'){let m=mode==='Padrão'?state.settings.taxMode:mode;if(m==='Manual')return num(state.settings.manualTax);return effectiveTax(state.settings.rbt12,m==='III'?'III':'V')}
const factorR=()=>state.settings.rbt12>0?state.settings.payroll12/state.settings.rbt12:0;
function monthlyCost(c){if(!c.active)return 0;if(c.period==='Anual')return num(c.value)/12;if(c.period==='Por cliente')return num(c.value)*num(c.qty);return num(c.value)}
const totalCosts=()=>state.costs.reduce((a,c)=>a+monthlyCost(c),0), fixedCosts=()=>state.costs.filter(c=>c.type==='Fixo').reduce((a,c)=>a+monthlyCost(c),0), variableCosts=()=>totalCosts()-fixedCosts();
const allocatedFixed=()=>state.settings.clientsPlanned>0?fixedCosts()/state.settings.clientsPlanned:0;
function priceCalc(p){const work=num(p.hours)*num(state.settings.hourValue),tax=taxRate(p.taxMode),taxValue=num(p.price)*tax,fixed=allocatedFixed(),base=work+num(p.tech)+num(p.variable)+fixed,total=base+taxValue,profit=num(p.price)-total,margin=p.price>0?profit/p.price:0,den=1-tax-num(state.settings.targetMargin),min=den>0?base/den:0,sustainable=(1-tax-.25)>0?base/(1-tax-.25):0;return{work,tax,taxValue,fixed,base,total,profit,margin,min,sustainable,status:p.price<=0?'Definir preço':profit<0?'Prejuízo':p.price<min?'Abaixo do alvo':'Saudável'}}
function clientMetrics(c){const revenue=num(c.monthlyRevenue),direct=num(c.directCost),tax=revenue*taxRate(),share=state.clients.filter(x=>x.status==='active').length?fixedCosts()/state.clients.filter(x=>x.status==='active').length:0,total=direct+tax+share,profit=revenue-total,margin=revenue?profit/revenue:0;return{revenue,direct,tax,share,total,profit,margin}}
function planMetrics(pl){const items=pl.items||[];let sum=0,cost=0;items.forEach(i=>{const p=state.products.find(x=>x.id===i.productId);if(!p)return;const q=num(i.qty)||1,pc=priceCalc(p);sum+=(i.customPrice??p.price)*q;cost+=(pc.base)*q});const price=sum*(1-num(pl.discount)),tax=price*taxRate(),profit=price-cost-tax,margin=price?profit/price:0;return{sum,price,cost,tax,profit,margin}}
function cashMetrics(){const paidIn=state.cashflow.filter(x=>x.type==='Entrada'&&x.status==='Pago').reduce((a,x)=>a+num(x.amount),0),paidOut=state.cashflow.filter(x=>x.type==='Saída'&&x.status==='Pago').reduce((a,x)=>a+num(x.amount),0),pendingIn=state.cashflow.filter(x=>x.type==='Entrada'&&x.status==='Pendente').reduce((a,x)=>a+num(x.amount),0),pendingOut=state.cashflow.filter(x=>x.type==='Saída'&&x.status==='Pendente').reduce((a,x)=>a+num(x.amount),0);return{paidIn,paidOut,pendingIn,pendingOut,balance:num(state.settings.cashOpening)+paidIn-paidOut,projected:num(state.settings.cashOpening)+paidIn-paidOut+pendingIn-pendingOut}}
function dre(period=monthKey()){const closing=state.closings.find(x=>x.month===period);if(closing)return closing;const gross=state.settings.revenueCurrent||state.clients.filter(c=>c.status==='active').reduce((a,c)=>a+num(c.monthlyRevenue),0),tax=gross*taxRate(),net=gross-tax,v=variableCosts()+state.clients.filter(c=>c.status==='active').reduce((a,c)=>a+num(c.directCost),0),contrib=net-v,f=fixedCosts(),result=contrib-f;return{month:period,grossRevenue:gross,taxes:tax,netRevenue:net,variableCosts:v,contribution:contrib,fixedCosts:f,operatingResult:result,margin:gross?result/gross:0}}
function healthScore(){let s=45,rev=state.settings.revenueProjected,tc=totalCosts();if(tc>0)s+=5;if(rev>0){const cash=rev-tc-rev*taxRate();s+=cash>0?20:-20;s+=tc/rev<.5?10:-5}if(state.products.filter(p=>p.price>0).length>=3)s+=10;if(state.clients.some(c=>c.status==='active'))s+=5;if(state.products.some(p=>p.price>0&&priceCalc(p).profit<0))s-=10;return Math.max(0,Math.min(100,s))}
function alerts(){const a=[],rev=state.settings.revenueProjected,tc=totalCosts();if(rev>0&&tc/rev>state.settings.costAlert)a.push(['critical','Custos altos',`Custos representam ${pct(tc/rev)} da receita projetada.`]);state.products.forEach(p=>{const c=priceCalc(p);if(p.price>0&&c.profit<0)a.push(['critical','Produto em prejuízo',`${p.name}: ${brl(c.profit)} de resultado estimado.`]);else if(p.price>0&&p.price<c.min)a.push(['warning','Margem abaixo do alvo',`${p.name} está abaixo do preço mínimo ${brl(c.min)}.`])});state.clients.filter(c=>c.status==='active').forEach(c=>{const m=clientMetrics(c);if(m.profit<0)a.push(['critical','Cliente com margem negativa',`${c.name}: ${brl(m.profit)}.`])});const totalClient=state.clients.filter(c=>c.status==='active').reduce((a,c)=>a+num(c.monthlyRevenue),0);if(totalClient>0){const top=[...state.clients].filter(c=>c.status==='active').sort((a,b)=>b.monthlyRevenue-a.monthlyRevenue)[0];if(top&&top.monthlyRevenue/totalClient>state.settings.concentrationAlert)a.push(['warning','Concentração de receita',`${top.name} representa ${pct(top.monthlyRevenue/totalClient)} da receita de clientes.`])}return a.slice(0,12)}

function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.append(e);setTimeout(()=>e.remove(),2300)}
const icons={dashboard:'▦',costs:'◫',products:'◇',clients:'◉',plans:'▤',cashflow:'↕',dre:'≋',scenarios:'◎',goals:'⌖',ai:'✦',audit:'☰',settings:'⚙'};
function nav(){const items=[['dashboard','Dashboard'],['costs','Custos'],['products','Produtos'],['clients','Clientes'],['plans','Planos'],['cashflow','Fluxo de caixa'],['dre','DRE'],['scenarios','Cenários'],['goals','Metas'],['ai','CFO IA'],['audit','Auditoria'],['settings','Configuração']];return `<aside class="sidebar"><div class="brand"><div class="brand-badge">Z</div><div><h1>Zahav Finance OS</h1><small>Financeiro & Precificação</small></div></div><div class="nav">${items.map(([k,l])=>`<button data-nav="${k}" class="${page===k?'active':''}"><span class="ico">${icons[k]}</span><span class="label">${l}</span></button>`).join('')}</div><div class="sidebar-foot"><b>Modo local ativo</b><br>Banco em nuvem preparado no Lovable/Supabase.</div></aside>`}
function layout(content,title,sub=''){return `<div class="app">${nav()}<main class="main"><header class="topbar"><div><div class="eyebrow">Zahav Digital</div><h2>${title}</h2>${sub?`<div class="muted">${sub}</div>`:''}</div><div class="actions"><span class="pill">${state.settings.size} • ${state.settings.taxMode==='V'?'Anexo V':state.settings.taxMode==='III'?'Anexo III':'Manual'}</span><button class="btn" id="exportBtn">Backup</button></div></header>${content}</main></div>`}
const kpi=(l,v,h,c='')=>`<div class="card kpi ${c}"><div class="label">${l}</div><div class="value">${v}</div><div class="hint">${h}</div></div>`;
const btn=(id,label,cls='primary')=>`<button class="btn ${cls}" id="${id}">${label}</button>`;

