function cashflowPage(){
 const cm=cashMetrics(),fc=cashForecast(90),minPoint=fc.points.length?Math.min(...fc.points.map(p=>p.balance),cm.balance):cm.balance;
 return layout(`<div class="grid kpis">${kpi('Saldo realizado',brl(cm.balance),'Saldo inicial + pagos')}${kpi('Entradas pendentes',brl(cm.pendingIn),'A receber')}${kpi('Saídas pendentes',brl(cm.pendingOut),'A pagar')}${kpi('Projeção 90 dias',brl(fc.projected),`Pior ponto ${brl(minPoint)}`,fc.projected<0?'negative':'positive')}</div>
 <div class="grid two"><section class="card"><div class="section-title"><div><h3>Fluxo de caixa</h3><div class="sub">Previsto, realizado e recorrente.</div></div><div class="actions">${btn('exportCashCsv','CSV','')}${btn('addCash','+ Novo lançamento')}</div></div><div class="table-wrap"><table><thead><tr><th>Vencimento</th><th>Tipo</th><th>Descrição</th><th>Recorrência</th><th>Status</th><th>Valor</th><th></th></tr></thead><tbody>${state.cashflow.length?[...state.cashflow].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).map(x=>`<tr><td>${x.dueDate}</td><td>${esc(x.type)}</td><td><b>${esc(x.description)}</b><small>${esc(x.category)}</small></td><td>${esc(x.recurrence||'Não recorrente')}</td><td>${statusBadge(x.status)}</td><td>${brl(x.amount)}</td><td><button class="icon-btn" data-edit-cash="${x.id}">✎</button><button class="icon-btn" data-toggle-paid="${x.id}" title="Marcar pago/pendente">✓</button></td></tr>`).join(''):emptyRow(7,'Nenhum lançamento ainda.')}</tbody></table></div></section>
 <section class="card"><h3>Próximos 90 dias</h3><div class="sub">Inclui repetições mensais, semanais e anuais.</div><div class="forecast-list">${fc.entries.slice(0,12).map(e=>`<div class="list-line"><span>${e.forecastDate} • ${esc(e.description)}</span><b class="${e.type==='Saída'?'neg':''}">${e.type==='Saída'?'-':'+'}${brl(e.amount)}</b></div>`).join('')||'<div class="empty">Sem movimentações previstas.</div>'}</div></section></div>`,`Fluxo de caixa`,`Controle de entradas, saídas e projeção de 90 dias`);
}


function drePage(){
 const cmp=dreComparison(),d=cmp.current,rows=[['Receita bruta',d.grossRevenue],['(-) Impostos',-d.taxes],['Receita líquida',d.netRevenue],['(-) Custos variáveis',-d.variableCosts],['Margem de contribuição',d.contribution],['(-) Custos fixos',-d.fixedCosts],['Resultado operacional',d.operatingResult]];
 return layout(`<div class="grid two"><section class="card"><div class="section-title"><div><h3>DRE gerencial</h3><div class="sub">Mês atual / cenário calculado.</div></div>${btn('closeMonth','Fechar mês','')}</div><div class="dre-list">${rows.map((r,i)=>`<div class="${i===2||i===4||i===6?'total':''}"><span>${r[0]}</span><b class="${r[1]<0?'neg':''}">${brl(r[1])}</b></div>`).join('')}</div></section><section class="card"><h3>Comparativo</h3><div class="summary-list"><div><span>Margem operacional</span><b>${pct(d.margin)}</b></div><div><span>Margem de contribuição</span><b>${d.grossRevenue?pct(d.contribution/d.grossRevenue):'0%'}</b></div><div><span>Receita vs último fechamento</span><b>${cmp.previous?pct(cmp.revenueDelta):'-'}</b></div><div><span>Resultado vs último fechamento</span><b>${cmp.previous?pct(cmp.resultDelta):'-'}</b></div><div><span>Meses fechados</span><b>${state.closings.length}</b></div></div></section></div>
 <section class="card"><h3>Histórico de fechamentos</h3><div class="table-wrap"><table><thead><tr><th>Mês</th><th>Receita</th><th>Impostos</th><th>Custos</th><th>Resultado</th><th>Margem</th></tr></thead><tbody>${state.closings.length?[...state.closings].sort((a,b)=>b.month.localeCompare(a.month)).map(x=>`<tr><td>${x.month.slice(0,7)}</td><td>${brl(x.grossRevenue)}</td><td>${brl(x.taxes)}</td><td>${brl(x.variableCosts+x.fixedCosts)}</td><td>${brl(x.operatingResult)}</td><td>${pct(x.margin)}</td></tr>`).join(''):emptyRow(6,'Nenhum fechamento registrado.')}</tbody></table></div></section>`,`DRE & Fechamentos`,`Resultado gerencial mensal e comparação histórica`);
}


function indicatorsPage(){
 const i=indicators();
 return layout(`<div class="grid kpis">${kpi('MRR',brl(i.mrr),'Receita recorrente')}${kpi('Ticket médio',brl(i.ticket),'Por cliente ativo')}${kpi('CAC informado',brl(i.cac),'Aquisição por cliente')}${kpi('LTV estimado',brl(i.ltv),`${state.settings.avgRetentionMonths} meses de retenção`)}</div>
 <div class="grid three"><section class="card"><h3>Eficiência comercial</h3><div class="summary-list"><div><span>Payback CAC</span><b>${i.payback?`${i.payback.toFixed(1)} meses`:'-'}</b></div><div><span>Churn histórico simples</span><b>${pct(i.churn)}</b></div><div><span>Concentração de receita</span><b>${pct(i.revenueConcentration)}</b></div><div><span>Ponto de equilíbrio</span><b>${brl(i.breakEven)}</b></div></div></section><section class="card"><h3>Capacidade</h3><div class="summary-list"><div><span>Horas recorrentes estimadas</span><b>${i.soldHours.toFixed(1)}h</b></div><div><span>Capacidade mensal</span><b>${i.capacity.toFixed(0)}h</b></div><div><span>Utilização</span><b>${pct(i.utilization)}</b></div><div><span>Tecnologia / cliente</span><b>${brl(i.toolPerClient)}</b></div></div></section><section class="card"><h3>Rentabilidade</h3><div class="summary-list"><div><span>Margem média clientes</span><b>${pct(i.avgMargin)}</b></div><div><span>Custo total ferramentas</span><b>${brl(i.toolCost)}</b></div><div><span>LTV / CAC</span><b>${i.cac?`${(i.ltv/i.cac).toFixed(1)}x`:'-'}</b></div><div><span>Saúde financeira</span><b>${healthScore()}/100</b></div></div></section></div>`,`Indicadores`,`CAC, LTV, churn, payback, capacidade e concentração`);
}
