function dashboard(){
 const s=state.settings,tc=totalCosts(),cm=cashMetrics(),forecast=cashForecast(90),d=dre(),score=healthScore(),als=alerts(),ind=indicators();
 return layout(`<div class="hero"><div><h3>Preço, caixa e crescimento na mesma visão.</h3><p>Use a operação real para decidir quando aumentar preço, contratar, investir ou cortar custos.</p></div><div class="hero-stat"><span>Saúde financeira</span><strong>${score}/100</strong><small>${score>=75?'Boa base':score>=55?'Em construção':'Precisa de ajustes'}</small></div></div>
 <div class="grid kpis mt">${kpi('Custo mensal',brl(tc),'Estrutura atual')}${kpi('MRR clientes',brl(ind.mrr),`${activeClients().length} clientes ativos`)}${kpi('Caixa em 90 dias',brl(forecast.projected),'Projeção com recorrências',forecast.projected<0?'negative':'positive')}${kpi('Resultado operacional',brl(d.operatingResult),`Margem ${pct(d.margin)}`,d.operatingResult<0?'negative':'positive')}</div>
 <div class="grid two"><section class="card"><div class="section-title"><div><h3>Alertas automáticos</h3><div class="sub">Prioridades que merecem ação.</div></div><span class="badge">${als.length}</span></div>${als.length?als.map(a=>`<div class="alert-row ${a.severity}"><div><b>${esc(a.title)}</b><span>${esc(a.message)}</span></div><button class="icon-btn" title="Resolver" data-resolve-alert="${esc(a.id)}">✓</button></div>`).join(''):'<div class="empty">Nenhum alerta crítico com os dados atuais.</div>'}</section>
 <section class="card"><h3>Resumo da operação</h3><div class="summary-list"><div><span>Ticket médio</span><b>${brl(ind.ticket)}</b></div><div><span>Ponto de equilíbrio</span><b>${brl(ind.breakEven)}</b></div><div><span>Concentração maior cliente</span><b>${pct(ind.revenueConcentration)}</b></div><div><span>Fator R estimado</span><b>${pct(factorR())}</b></div><div><span>Alíquota gerencial</span><b>${pct(taxRate())}</b></div><div><span>Rateio fixo / cliente</span><b>${brl(actualAllocatedFixed()||allocatedFixed())}</b></div></div></section></div>`,`Dashboard`,`Visão executiva da Zahav`);
}


function costsPage(){
 const total=totalCosts();
 return layout(`<section class="card"><div class="section-title"><div><h3>Custos da Zahav</h3><div class="sub">Peso no custo total e na receita projetada.</div></div><div class="actions">${btn('exportCostsCsv','CSV','')}${btn('addCost','+ Novo custo')}</div></div><div class="table-wrap"><table><thead><tr><th>Despesa</th><th>Categoria</th><th>Tipo</th><th>Periodicidade</th><th>Mensal</th><th>% custo</th><th>% receita</th><th></th></tr></thead><tbody>${state.costs.map(c=>{const m=monthlyCost(c);return `<tr class="${c.active===false?'muted-row':''}"><td><b>${esc(c.name)}</b><small>${esc(c.supplier||c.center||'')}</small></td><td>${esc(c.category)}</td><td>${esc(c.type)}</td><td>${esc(c.period)}</td><td>${brl(m)}</td><td>${total?pct(m/total):'-'}</td><td>${state.settings.revenueProjected?pct(m/state.settings.revenueProjected):'-'}</td><td><button class="icon-btn" data-edit-cost="${c.id}">✎</button><button class="icon-btn danger" data-del-cost="${c.id}">×</button></td></tr>`}).join('')}</tbody></table></div></section>`,`Custos`,`Tudo que consome caixa ou capacidade operacional`);
}


function productsPage(){
 return layout(`<section class="card"><div class="section-title"><div><h3>Produtos & precificação</h3><div class="sub">Preço mínimo, piso de caixa e preço sustentável por produto.</div></div><div class="actions">${btn('exportProductsCsv','CSV','')}${btn('addProduct','+ Novo produto')}</div></div><div class="table-wrap"><table><thead><tr><th>Produto</th><th>Venda</th><th>Piso caixa</th><th>Preço mínimo</th><th>Sustentável 25%</th><th>Margem</th><th>Status</th><th></th></tr></thead><tbody>${state.products.map(p=>{const c=priceCalc(p);return `<tr><td><b>${esc(p.name)}</b><small>${esc(p.model)} • ${num(p.hours)}h</small></td><td>${brl(p.price)}</td><td>${brl(c.cashFloor)}</td><td>${brl(c.min)}</td><td>${brl(c.sustainable)}</td><td>${pct(c.margin)}</td><td>${statusBadge(c.status)}</td><td><button class="icon-btn" data-edit-product="${p.id}">✎</button><button class="icon-btn" data-save-price-version="${p.id}" title="Registrar versão de preço">⎙</button></td></tr>`}).join('')}</tbody></table></div></section>`,`Produtos`,`Margem por produto e preço de validação`);
}


function clientsPage(){
 const active=activeClients(),ind=indicators();
 return layout(`<div class="grid kpis">${kpi('Clientes ativos',active.length,'Carteira recorrente')}${kpi('MRR informado',brl(ind.mrr),'Receita mensal dos clientes')}${kpi('Ticket médio',brl(ind.ticket),'MRR ÷ ativos')}${kpi('Margem média',pct(ind.avgMargin),'Após custos e imposto')}</div>
 <section class="card"><div class="section-title"><div><h3>Clientes</h3><div class="sub">Receita, custo, plano e rentabilidade individual.</div></div><div class="actions">${btn('exportClientsCsv','CSV','')}${btn('addClient','+ Novo cliente')}</div></div><div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Status</th><th>Plano / produtos</th><th>Mensalidade</th><th>Custo direto</th><th>Lucro est.</th><th>Margem</th><th></th></tr></thead><tbody>${state.clients.length?state.clients.map(c=>{const m=clientMetrics(c),pl=state.plans.find(p=>p.id===c.planId),ps=(c.productIds||[]).map(id=>state.products.find(p=>p.id===id)?.name).filter(Boolean);return `<tr><td><b>${esc(c.name)}</b><small>${esc(c.document||c.notes||'')}</small></td><td>${statusBadge(c.status)}</td><td>${esc(pl?.name||ps.join(', ')||'-')}</td><td>${brl(c.monthlyRevenue)}</td><td>${brl(c.directCost)}</td><td>${brl(m.profit)}</td><td>${pct(m.margin)}</td><td><button class="icon-btn" data-edit-client="${c.id}">✎</button></td></tr>`}).join(''):emptyRow(8,'Cadastre o primeiro cliente para medir margem real da carteira.')}</tbody></table></div></section>`,`Clientes`,`Rentabilidade por cliente, mix de produtos e concentração de receita`);
}


function plansPage(){
 return layout(`<section class="card"><div class="section-title"><div><h3>Planos & combos</h3><div class="sub">Start, Growth, Scale, Premium ou qualquer combinação de produtos.</div></div>${btn('addPlan','+ Novo plano')}</div><div class="plan-grid">${state.plans.length?state.plans.map(pl=>{const m=planMetrics(pl);return `<article class="plan-card"><div class="plan-head"><div><h3>${esc(pl.name)}</h3><small>${esc(pl.description||'')}</small></div><button class="icon-btn" data-edit-plan="${pl.id}">✎</button></div><div class="plan-price">${brl(m.price)}<small>/ combo</small></div><div class="summary-list"><div><span>Soma individual</span><b>${brl(m.sum)}</b></div><div><span>Desconto</span><b>${pct(pl.discount)}</b></div><div><span>Custo base</span><b>${brl(m.cost)}</b></div><div><span>Horas estimadas</span><b>${m.hours.toFixed(1)}h</b></div><div><span>Lucro estimado</span><b>${brl(m.profit)}</b></div><div><span>Margem</span><b>${pct(m.margin)}</b></div></div></article>`}).join(''):'<div class="empty">Monte seus combos somente depois de precificar os produtos individuais.</div>'}</div></section>`,`Planos`,`Combos sem perder visibilidade da margem`);
}
