function localAnswer(q){
 const t=q.toLowerCase(),out=[],ind=indicators(),fc=cashForecast(90);
 if(t.includes('20 mil')||t.includes('20000')){const ticket=ind.ticket||state.products.filter(p=>p.model==='Mensal'&&p.price>0).reduce((a,p)=>a+p.price,0)/Math.max(1,state.products.filter(p=>p.model==='Mensal'&&p.price>0).length);out.push(ticket?`Com ticket médio de ${brl(ticket)}, são aproximadamente ${Math.ceil(20000/ticket)} clientes ativos para chegar a R$ 20 mil/mês.`:'Defina preços ou clientes para calcular o ticket médio.')}
 if(t.includes('contrat')){const rev=state.settings.revenueProjected,free=rev-totalCosts()-rev*taxRate();out.push(free>0?`No cenário projetado sobram ${brl(free)} antes de uma nova contratação. Eu compararia o custo total mensal da pessoa com essa folga e exigiria receita recorrente suficiente para manter pelo menos 2 a 3 meses de segurança.`:`O cenário projetado ainda não mostra folga: ${brl(free)} antes da contratação.`)}
 if(t.includes('caixa')&&(t.includes('90')||t.includes('próxim'))){out.push(`A projeção de caixa para 90 dias termina em ${brl(fc.projected)}, partindo de saldo realizado de ${brl(fc.current)} e considerando ${fc.entries.length} movimentações previstas/recorrentes.`)}
 if(t.includes('cliente')&&t.includes('margem')){const arr=activeClients().map(c=>[c,clientMetrics(c)]).sort((a,b)=>a[1].margin-b[1].margin);if(arr[0])out.push(`${arr[0][0].name} tem a menor margem estimada: ${pct(arr[0][1].margin)}, com ${brl(arr[0][1].profit)} de resultado mensal.`)}
 if(t.includes('produto')||t.includes('cobrar')||t.includes('preço')){const arr=state.products.map(p=>[p,priceCalc(p)]).filter(x=>x[0].price>0).sort((a,b)=>a[1].margin-b[1].margin);if(arr[0])out.push(`${arr[0][0].name} merece atenção: vende por ${brl(arr[0][0].price)}, piso de caixa ${brl(arr[0][1].cashFloor)}, preço mínimo ${brl(arr[0][1].min)} e margem ${pct(arr[0][1].margin)}.`)}
 if(t.includes('ltv')||t.includes('cac'))out.push(`CAC informado: ${brl(ind.cac)}. LTV estimado: ${brl(ind.ltv)}. Relação LTV/CAC: ${ind.cac?(ind.ltv/ind.cac).toFixed(1)+'x':'não calculada porque o CAC está zerado'}.`);
 if(!out.length)out.push(`Hoje a Zahav tem custo mensal de ${brl(totalCosts())}, imposto gerencial de ${pct(taxRate())}, ${activeClients().length} clientes ativos, MRR de ${brl(ind.mrr)} e saúde financeira ${healthScore()}/100.`);
 out.push('Use esta análise como gestão interna e valide o tratamento tributário com a contabilidade.');return out.join(' ');
}

async function askAI(){const q=$('#aiQuestion').value.trim(),box=$('#aiAnswer');if(!q)return;box.style.display='block';box.textContent='Analisando...';try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,state})});if(r.ok){const d=await r.json();box.textContent=d.answer||localAnswer(q)}else box.textContent=localAnswer(q)}catch{box.textContent=localAnswer(q)}state.aiHistory.unshift({id:uid(),at:new Date().toISOString(),question:q,answer:box.textContent});state.aiHistory=state.aiHistory.slice(0,100);persist()}

async function cloudDialog(){
 if(!Cloud.config)await Cloud.loadConfig();
 if(!Cloud.config){alert('A nuvem está preparada, mas SUPABASE_URL e SUPABASE_ANON_KEY ainda não estão configurados na hospedagem. O modo local continua funcionando normalmente.');return}
 Cloud.restoreSession();
 if(Cloud.session&&state.cloud.organizationId){const bg=modal(`<div class="modal-head"><div><h3>Nuvem Zahav</h3><div class="sub">${esc(state.cloud.user?.email||'Usuário autenticado')}</div></div><button class="x">×</button></div><div class="summary-list"><div><span>Última sincronização</span><b>${state.cloud.lastSync?new Date(state.cloud.lastSync).toLocaleString('pt-BR'):'Nunca'}</b></div><div><span>Organização</span><b>${esc(state.cloud.organizationId||'-')}</b></div></div><div class="modal-actions mt"><button class="btn primary" id="cloudPush">Enviar dados locais</button><button class="btn" id="cloudPull">Baixar dados da nuvem</button><button class="btn danger" id="cloudLogout">Sair</button></div>`);$('#cloudPush',bg).onclick=async()=>{try{await Cloud.pushSnapshot();bg.remove();render();toast('Dados enviados à nuvem.')}catch(e){alert(e.message)}};$('#cloudPull',bg).onclick=async()=>{if(!confirmAction('Substituir os dados locais pelos dados da nuvem?'))return;try{await Cloud.pull();bg.remove();toast('Dados baixados da nuvem.')}catch(e){alert(e.message)}};$('#cloudLogout',bg).onclick=()=>{Cloud.signOut();bg.remove();toast('Sessão encerrada.')};return}
 const bg=authModal();$('#loginCloud',bg).onclick=async()=>{const msg=$('#authMessage',bg);try{msg.textContent='Entrando...';await Cloud.signIn($('#authEmail',bg).value,$('#authPassword',bg).value);bg.remove();render();toast('Nuvem conectada.')}catch(e){msg.textContent=e.message}};$('#signupCloud',bg).onclick=async()=>{const msg=$('#authMessage',bg);try{msg.textContent='Criando conta...';const r=await Cloud.signUp($('#authEmail',bg).value,$('#authPassword',bg).value);if(r.access_token){bg.remove();render();toast('Conta criada e conectada.')}else msg.textContent='Conta criada. Verifique o e-mail se a confirmação estiver habilitada.'}catch(e){msg.textContent=e.message}};
}
