function savePriceVersion(productId){
 const p=state.products.find(x=>x.id===productId);if(!p)return;const c=priceCalc(p),v={id:uid(),productId:p.id,createdAt:new Date().toISOString(),salePrice:num(p.price),targetMargin:num(state.settings.targetMargin),taxRate:c.tax,workCost:c.work,technologyCost:num(p.tech),variableCost:num(p.variable),allocatedFixed:c.fixed,totalCost:c.total,minimumPrice:c.min,calculatedMargin:c.margin,status:c.status};state.pricingVersions.unshift(v);state.pricingVersions=state.pricingVersions.slice(0,1000);audit('Registrar preço',p.name,null,v);render();toast('Versão de preço registrada.')}
function applyScenario(id){const s=state.scenarios.find(x=>x.id===id);if(!s)return;if(!confirmAction(`Aplicar o cenário ${s.name} à projeção atual?`))return;const before=structuredClone(state.settings);state.settings.clientsPlanned=Math.max(1,num(s.clients)||state.settings.clientsPlanned);state.settings.revenueProjected=Math.max(0,num(s.revenue)||num(s.clients)*num(s.ticket));audit('Aplicar cenário',s.name,before,structuredClone(state.settings));render();toast('Cenário aplicado à projeção.')}
function saveTaxTables(){['III','V'].forEach(annex=>{state.taxTables[annex]=state.taxTables[annex].map((row,i)=>{const limit=$(`[data-tax-limit="${annex}:${i}"]`),rate=$(`[data-tax-rate="${annex}:${i}"]`),ded=$(`[data-tax-deduction="${annex}:${i}"]`);return[Math.max(0,num(limit?.value)),clamp(num(rate?.value)/100,0,1),Math.max(0,num(ded?.value))]})});audit('Atualizar faixas fiscais','Simples Nacional');render();toast('Faixas fiscais salvas.')}
function resetTax(annex){if(!confirmAction(`Restaurar a tabela padrão do Anexo ${annex}?`))return;state.taxTables[annex]=structuredClone(DEFAULT_TAX_TABLES[annex]);audit('Restaurar tabela fiscal',`Anexo ${annex}`);render()}
function togglePaid(id){const e=state.cashflow.find(x=>x.id===id);if(!e)return;const before=structuredClone(e);e.status=e.status==='Pago'?'Pendente':'Pago';e.paidDate=e.status==='Pago'?today():'';audit('Alterar status caixa',e.description,before,structuredClone(e));render()}
function resolveAlert(id){if(!state.alertsResolved.includes(id))state.alertsResolved.push(id);persist();render();toast('Alerta marcado como resolvido.')}
function resetAll(){if(!confirmAction('Restaurar todos os dados locais? Esta ação não altera a nuvem.'))return;state=fresh();persist();render();toast('Dados locais restaurados.')}
function refreshOverdue(){const t=today();let changed=false;state.cashflow.forEach(e=>{if(e.status==='Pendente'&&e.dueDate&&e.dueDate<t){e.status='Vencido';changed=true}});if(changed)persist()}
async function initCloud(){try{await Cloud.loadConfig();Cloud.restoreSession();if(Cloud.session){try{await Cloud.loadProfile()}catch{Cloud.signOut()}}render()}catch{render()}}
function bind(){
 $$('[data-nav]').forEach(b=>b.onclick=()=>{page=b.dataset.nav;render()});
 $('#exportBtn')?.addEventListener('click',exportData);
 $('#addCost')?.addEventListener('click',()=>costModal());$$('[data-edit-cost]').forEach(b=>b.onclick=()=>costModal(state.costs.find(c=>c.id===b.dataset.editCost)));$$('[data-del-cost]').forEach(b=>b.onclick=()=>{const c=state.costs.find(x=>x.id===b.dataset.delCost);if(c&&confirmAction('Excluir custo?')){state.costs=state.costs.filter(x=>x.id!==c.id);audit('Excluir custo',c.name,c,null);render()}});
 $('#addProduct')?.addEventListener('click',()=>productModal());$$('[data-edit-product]').forEach(b=>b.onclick=()=>productModal(state.products.find(p=>p.id===b.dataset.editProduct)));$$('[data-save-price-version]').forEach(b=>b.onclick=()=>savePriceVersion(b.dataset.savePriceVersion));
 $('#addClient')?.addEventListener('click',()=>clientModal());$$('[data-edit-client]').forEach(b=>b.onclick=()=>clientModal(state.clients.find(c=>c.id===b.dataset.editClient)));
 $('#addPlan')?.addEventListener('click',()=>planModal());$$('[data-edit-plan]').forEach(b=>b.onclick=()=>planModal(state.plans.find(p=>p.id===b.dataset.editPlan)));
 $('#addCash')?.addEventListener('click',()=>cashModal());$$('[data-edit-cash]').forEach(b=>b.onclick=()=>cashModal(state.cashflow.find(c=>c.id===b.dataset.editCash)));$$('[data-toggle-paid]').forEach(b=>b.onclick=()=>togglePaid(b.dataset.togglePaid));
 $('#closeMonth')?.addEventListener('click',closeMonth);
 $('#addScenario')?.addEventListener('click',()=>scenarioModal());$$('[data-del-scenario]').forEach(b=>b.onclick=()=>{const s=state.scenarios.find(x=>x.id===b.dataset.delScenario);if(s&&confirmAction('Excluir cenário?')){state.scenarios=state.scenarios.filter(x=>x.id!==s.id);audit('Excluir cenário',s.name,s,null);render()}});$$('[data-apply-scenario]').forEach(b=>b.onclick=()=>applyScenario(b.dataset.applyScenario));
 $('#addGoal')?.addEventListener('click',()=>goalModal('Mensal'));$('#addAnnualGoal')?.addEventListener('click',()=>goalModal('Anual'));
 $('#saveTaxTables')?.addEventListener('click',saveTaxTables);$('#resetTaxIII')?.addEventListener('click',()=>resetTax('III'));$('#resetTaxV')?.addEventListener('click',()=>resetTax('V'));
 $('#saveSettings')?.addEventListener('click',saveSettings);$('#resetBtn')?.addEventListener('click',resetAll);$('#connectCloud')?.addEventListener('click',cloudDialog);
 $('#importBtn')?.addEventListener('click',()=>$('#importFile')?.click());$('#importFile')?.addEventListener('change',importData);$('#importCsvBtn')?.addEventListener('click',()=>$('#importCsvFile')?.click());$('#importCsvFile')?.addEventListener('change',importCsvFile);
 $('#exportCostsCsv')?.addEventListener('click',()=>exportEntityCsv('costs'));$('#exportProductsCsv')?.addEventListener('click',()=>exportEntityCsv('products'));$('#exportClientsCsv')?.addEventListener('click',()=>exportEntityCsv('clients'));$('#exportCashCsv')?.addEventListener('click',()=>exportEntityCsv('cash'));$('#exportAuditCsv')?.addEventListener('click',()=>exportEntityCsv('audit'));
 $('#askAI')?.addEventListener('click',askAI);$$('[data-q]').forEach(b=>b.onclick=()=>{const q=$('#aiQuestion');if(q){q.value=b.dataset.q;askAI()}});$$('[data-resolve-alert]').forEach(b=>b.onclick=()=>resolveAlert(b.dataset.resolveAlert));
}
refreshOverdue();render();initCloud();
